package com.ddu.bean;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ddu.bean.StudyContent;

import com.ddu.bean.StudyContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studyContentDaoConfig;

    private final StudyContentDao studyContentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studyContentDaoConfig = daoConfigMap.get(StudyContentDao.class).clone();
        studyContentDaoConfig.initIdentityScope(type);

        studyContentDao = new StudyContentDao(studyContentDaoConfig, this);

        registerDao(StudyContent.class, studyContentDao);
    }
    
    public void clear() {
        studyContentDaoConfig.getIdentityScope().clear();
    }

    public StudyContentDao getStudyContentDao() {
        return studyContentDao;
    }

}
